# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Devaraj Phukan
title: Data Scientist(ish)
email: devaraj.phukan@gmail.com
phone:

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  devarajphukan
stackoverflow_username: "5116430"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: devarajphukan
linkedin_username: devarajphukan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 500px
  icon: fas fa-camera
  url: https://500px.com/p/devarajphukan
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Devaraj and I'm a Grad Student at RWTH Aachen University pursuing M.Sc Data Analytics & Decision Science. I have 3 years of full time working experince as a Data Science Engineer. And I do

  I am most skilled in: <mark>R</mark> and <mark>Python</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome personal website (COMING SOON !!!)
        link:
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          "Wow!, Great website"
                           |-me, circa 2021 A.D
        description: | # this will include new lines to allow paragraphs
          Learning to create a great personal website using jekyll, github pages, and looking for free/cheap templates for this website.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Manufacturing System Insights (VIMANA)
        link: https://govimana.com/
        # link_text: boringcompany.com
        sub_title: Software Developer (Data Science)
        caption: July 2017 - June 2020
        quote: >
          Industry 4.0 data science & analytics for manufacturing
        description: | # this will include new lines to allow paragraphs
            This was my first full time experince right after college, learnt to work in an Agile environment using tools which the real professionals do (like github/JIRA), and wrinting code without naming the variables (i,j,k). Tested & Deployed most of the stuff I built. Learnt to write some clean code after endless PR reviews using <mark>R</mark> & <mark>Python</mark>.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RWTH Aachen University
        caption: 2020 - present
        sub_title: M.Sc Data Analytics & Decision Science
        link: https://www.business-school.rwth-aachen.de/en/programs/m-sc-data-analytics-and-decision-science/
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |  Learning about Operations Research, Machine Learning, Deep Learning, and Management Science.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Data Science and software engineering some of my other interests and hobbies are:
      - Photography
      - Gaming (noob)
      - Gym (lol)

#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
